Models/GioHang.cs
namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("GioHang")]
    public partial class GioHang
    {
        [Key]
        public int magiohang { get; set; }

        public int masp { get; set; }

        public int makhachhang { get; set; }

        public int soluong { get; set; }

        public virtual KhachHang KhachHang { get; set; }

        public virtual SanPham SanPham { get; set; }
    }
}

Controllers/GioHangsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAn.Models;
using DoAn.PayMethod;

namespace DoAn.Controllers
{
    public class GioHangsController : Controller
    {
        private Model1 db = new Model1();

        // GET: GioHangs
        public ActionResult Index()
        {
            var gioHangs = db.GioHangs.Include(g => g.KhachHang).Include(g => g.SanPham);
            return View(gioHangs.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult RemoveCart(int magiohang)
        {
            GioHang gh = db.GioHangs.Where(s=>s.magiohang == magiohang).FirstOrDefault();
            db.GioHangs.Remove(gh);
            db.SaveChanges();
            Session["giohang"] = (int)Session["giohang"] - 1;
            return Json(new { success = true });
        }

        public ActionResult UpdateCart([Bind(Include = "magiohang,masp,makhachhang,soluong")] GioHang gioHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gioHang).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { success = true });
                
            }
            return RedirectToAction("Index");
        }

        public ActionResult ThanhToan()
        {
            var gioHangs = db.GioHangs.Include(g => g.KhachHang).Include(g => g.SanPham);
            KhachHang taikhoan = db.KhachHangs.Find((int)Session["ma"]);
            ViewBag.taikhoan = taikhoan;
            return View(gioHangs.ToList());
        }

        public ActionResult DatHang()
        {
            
            KhachHang taikhoan = db.KhachHangs.Find((int)Session["ma"]);
            List<GioHang> dssp = db.GioHangs.Where(s => s.makhachhang == taikhoan.makhachhang).ToList();
            decimal tongtien = 0;
            foreach (var item in dssp)
            {
                tongtien = tongtien + (decimal)(item.SanPham.giaban * item.soluong);
            }
            DonHang donHang = new DonHang();
            //string thanhtoan = Request.Form["thanhtoan"];
            //if (thanhtoan == "cod")
            //{
            //    donHang.thanhtoan = "Thanh toán khi nhận hàng";
            //}
            //else if(thanhtoan == "banking")
            //{
            //    donHang.thanhtoan = "Chuyển Khoản";
            //}
            donHang.makhachhang = taikhoan.makhachhang;
            
            donHang.diachi = Request.Form["diachi"] +", " + Request.Form["phuongxa"] + ", " + Request.Form["huyen"] + "," + Request.Form["thanhpho"];
            donHang.tongtien = tongtien;
            donHang.trangthai = false;
            donHang.thanhtoan = "Thanh toán khi nhận hàng";
            donHang.ngaydat = DateTime.Now;
            donHang.ngaynhan = donHang.ngaydat.AddDays(3);     
            taikhoan.diachi = Request.Form["dienthoai"];
            taikhoan.tinh = Request.Form["thanhpho"];
            taikhoan.huyen = Request.Form["huyen"];
            taikhoan.xa = Request.Form["phuongxa"];
            taikhoan.thon = Request.Form["diachi"];
            donHang.dienthoai = Request.Form["dienthoai"];
            taikhoan.dienthoai = donHang.dienthoai;
            db.DonHangs.Add(donHang);
            db.SaveChanges();
            var strSanPham = "";
            foreach (var item in dssp)
            {
                DonHangChiTiet dhct = new DonHangChiTiet();
                dhct.madonhang = donHang.madonhang;
                dhct.masp = item.masp;
                dhct.soluong = item.soluong;
                dhct.gia = item.SanPham.giaban;
                var sanpham = db.SanPhams.Find(item.masp);
                sanpham.soluong = sanpham.soluong - item.soluong;

                //data to send mail
                strSanPham += "<tr>";
                strSanPham += "<td>" + item.SanPham.tensp + "</td>";
                strSanPham += "<td>" + item.soluong + "</td>";
                strSanPham += "<td>" + item.SanPham.giaban + "</td>";
                strSanPham += "</tr>";

                db.GioHangs.Remove(item);
                db.DonHangChiTiets.Add(dhct);
                db.SaveChanges();
            }
            Session["giohang"] = 0;

            //send mail
            string contentCustomer = System.IO.File.ReadAllText(Server.MapPath("~/Content/Template/send2.html"));
            contentCustomer = contentCustomer.Replace("{{madon}}", donHang.madonhang.ToString());
            contentCustomer = contentCustomer.Replace("{{sanpham}}", strSanPham);
            contentCustomer = contentCustomer.Replace("{{hoten}}", taikhoan.hoten);
            contentCustomer = contentCustomer.Replace("{{ngaydat}}", donHang.ngaydat.ToString());
            contentCustomer = contentCustomer.Replace("{{tongtien}}", tongtien.ToString("#,##0"));
            contentCustomer = contentCustomer.Replace("{{diachi}}", donHang.diachi);
            contentCustomer = contentCustomer.Replace("{{dienthoai}}", taikhoan.dienthoai);
            contentCustomer = contentCustomer.Replace("{{email}}", taikhoan.email);
            DoAn.Common.MailHeper.sendEmail("An Phát Computer", "Đơn Hàng #" + donHang.madonhang, contentCustomer.ToString(), taikhoan.email);
            //string url = UrlPayment(1, donHang.madonhang);

            return RedirectToAction("Index", "DonHangs");
            //return Json(new { success = true });
        }

        public ActionResult DatHang1()
        {

            List<DonHangChiTiet> dhct = db.DonHangChiTiets.ToList();
            foreach (var item in dhct)
            {
                db.DonHangChiTiets.Remove(item);
            }
            List<DonHang> dh = db.DonHangs.ToList();
            foreach (var item in dh)
            {
                db.DonHangs.Remove(item);
            }
            db.SaveChanges();

            return RedirectToAction("Index", "DonHangs");
        }

        public string UrlPayment(int typePayment, int orderID)
        {
            var urlPayment = "";
            DonHang donHang = db.DonHangs.FirstOrDefault(d => d.madonhang == orderID);

            //Get Config Info
            string vnp_Returnurl = ConfigurationManager.AppSettings["vnp_Returnurl"]; //URL nhan ket qua tra ve 
            string vnp_Url = ConfigurationManager.AppSettings["vnp_Url"]; //URL thanh toan cua VNPAY 
            string vnp_TmnCode = ConfigurationManager.AppSettings["vnp_TmnCode"]; //Ma định danh merchant kết nối (Terminal Id)
            string vnp_HashSecret = ConfigurationManager.AppSettings["vnp_HashSecret"]; //Secret Key

            //Build URL for VNPAY
            VnPayLibrary vnpay = new VnPayLibrary();

            vnpay.AddRequestData("vnp_Version", VnPayLibrary.VERSION);
            vnpay.AddRequestData("vnp_Command", "pay");
            vnpay.AddRequestData("vnp_TmnCode", vnp_TmnCode);
            vnpay.AddRequestData("vnp_Amount", (donHang.tongtien * 100).ToString()); //Số tiền thanh toán. Số tiền không mang các ký tự phân tách thập phân, phần nghìn, ký tự tiền tệ. Để gửi số tiền thanh toán là 100,000 VND (một trăm nghìn VNĐ) thì merchant cần nhân thêm 100 lần (khử phần thập phân), sau đó gửi sang VNPAY là: 10000000
            
            if (typePayment == 1)
            {
                vnpay.AddRequestData("vnp_BankCode", "VNPAYQR");
            }
            else if (typePayment == 2)
            {
                vnpay.AddRequestData("vnp_BankCode", "VNBANK");
            }
            else if (typePayment == 3)
            {
                vnpay.AddRequestData("vnp_BankCode", "INTCARD");
            }

            vnpay.AddRequestData("vnp_CreateDate", donHang.ngaydat.ToString("yyyyMMddHHmmss"));
            vnpay.AddRequestData("vnp_CurrCode", "VND");
            vnpay.AddRequestData("vnp_IpAddr", Utils.GetIpAddress());
            vnpay.AddRequestData("vnp_Locale", "vn");

            vnpay.AddRequestData("vnp_OrderInfo", "Thanh toan don hang: #DH" + donHang.madonhang);
            vnpay.AddRequestData("vnp_OrderType", "other"); //default value: other

            vnpay.AddRequestData("vnp_ReturnUrl", vnp_Returnurl);
            vnpay.AddRequestData("vnp_TxnRef", donHang.madonhang.ToString()); // Mã tham chiếu của giao dịch tại hệ thống của merchant. Mã này là duy nhất dùng để phân biệt các đơn hàng gửi sang VNPAY. Không được trùng lặp trong ngày

            //Add Params of 2.1.0 Version
            //Billing

            urlPayment = vnpay.CreateRequestUrl(vnp_Url, vnp_HashSecret);
            return urlPayment;
        }

        public ActionResult VnpayReturn()
        {
            return View();
        }

    }
}

Views/GioHangs/Index.cshtml
@model IEnumerable<DoAn.Models.GioHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    decimal TienHang = 0;
    Session["flag"] = 0;
}

<main class="main">
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="~/Home">Trang chủ</a></li>
                <li class="breadcrumb-item active" aria-current="page">Giỏ hàng</li>
            </ol>
        </div>
    </nav>

    <div class="page-content">
        <div class="cart">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <table class="table table-cart table-mobile">
                            <thead>
                                <tr>
                                    <th style="width: 500px;">Sản Phẩm</th>
                                    <th>Giá Bán</th>
                                    <th>Số Lượng</th>
                                    <th class="text-center">Thành Tiền</th>
                                    <th></th>
                                </tr>
                            </thead>

                            <tbody>
                                @if (Model != null && Model.Any())
                                {
                                    foreach (var item in Model)
                                    {
                                        if (item.makhachhang.ToString() == Session["ma"].ToString())
                                        {
                                            Session["flag"] = 0;
                                            <tr>
                                                <td class="product-col">
                                                    <div class="product">
                                                        <figure class="product-media">
                                                            <a href="#">
                                                                <img src="@Url.Content("~/wwwroot/images/" + item.SanPham.hinhanh)" alt="Product image">
                                                            </a>
                                                        </figure>

                                                        <h3 class="product-title">
                                                            <a href="#">@item.SanPham.tensp</a>
                                                        </h3>
                                                    </div>
                                                </td>
                                                <td class="price-col">
                                                    @{
                                                        decimal gia = (decimal)item.SanPham.giaban;
                                                        string giaformat = gia.ToString("#,##0");
                                                    }
                                                    @giaformat
                                                </td>
                                                <td class="quantity-col">
                                                    <div class="cart-product-quantity soluong" data-soluongsp="@item.SanPham.soluong" data-cart-id="@item.magiohang" data-product-id="@item.masp" data-user-id="@item.makhachhang">
                                                        <input type="number" class="form-control" id="soluong" value="@item.soluong" min="1" max="100" step="1" data-decimals="0" required>
                                                    </div>
                                                </td>
                                                <td class="total-col">
                                                    @{
                                                        decimal total = (decimal)item.SanPham.giaban * item.soluong;
                                                        string totalformat = total.ToString("#,##0");
                                                        TienHang = TienHang + total;
                                                    }
                                                    @totalformat
                                                </td>
                                                <td class="remove-col"><button class="btn-remove" data-cart-id="@item.magiohang"><i class="icon-close"></i></button></td>
                                            </tr>
                                        }
                                        else
                                        {
                                            Session["flag"] = 1;
                                        }
                                    }
                                }
                            </tbody>
                        </table>

                        @if ((int)Session["flag"] == 0)
                        {
                            <div class="cart-bottom">
                                <div class="cart-discount">
                                    <form action="#">
                                        <div class="input-group">
                                            <input type="text" class="form-control" required placeholder="Mã giảm giá">
                                            <div class="input-group-append">
                                                <button class="btn btn-outline-primary-2" type="submit"><i class="icon-long-arrow-right"></i></button>
                                            </div>
                                        </div>
                                    </form>
                                </div>

                                <a href="~/GioHangs/ThanhToan" class="btn btn-outline-dark-2" style="height: 50px;"><span>Thanh Toán</span></a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<script>
    $(document).ready(function() {
        $('.btn-remove').click(function() {
            var cartId = $(this).data('cart-id');
            $.ajax({
                url: '@Url.Action("RemoveCart", "GioHangs")',
                type: 'POST',
                data: { magiohang: cartId },
                success: function(result) {
                    if (result.success) {
                        location.reload();
                    }
                },
                error: function() {
                    alert('Đã xảy ra lỗi!');
                }
            });
        });

        $('.soluong').click(function () {
            var cartId = $(this).data('cart-id');
            var productId = $(this).data('product-id');
            var userId = $(this).data('user-id');
            var slcon = $(this).data('soluongsp');
            var sl = $(this).find('#soluong').val();
            if (sl <= slcon) {
                $.ajax({
                    url: '@Url.Action("UpdateCart", "GioHangs")',
                    type: 'POST',
                    data: { magiohang: cartId, masp: productId, makhachhang: userId, soluong: sl },
                    success: function (result) {
                        if (result.success) {
                            location.reload();
                        }
                    },
                    error: function () {
                        alert('Đã xảy ra lỗi!');
                    }
                });
            }
            else {
                toastr.warning("Số Lượng Hàng Không Đủ");
            }
        });
    });

</script>

Views/GioHangs/ThanhToan.cshtml
@model IEnumerable<DoAn.Models.GioHang>
@{
    ViewBag.Title = "ThanhToan";
    Layout = "~/Views/Shared/_Layout.cshtml";
    decimal TienHang = 0;
    var kh = ViewBag.taikhoan as DoAn.Models.KhachHang;
}

<main class="main">
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="~/Home/Index">Trang Chủ</a></li>
                <li class="breadcrumb-item"><a href="~/SanPhams">Sản Phẩm</a></li>
                <li class="breadcrumb-item active" aria-current="page">Thanh Toán</li>
            </ol>
        </div>
    </nav>

    <div class="page-content">
        <div class="checkout">
            <div class="container">
                <form action="/GioHangs/DatHang" method="post">
                    <div class="row">
                        <div class="col-lg-7">
                            <h2 class="checkout-title">Chi Tiết Thanh Toán</h2>

                            <label>Họ Tên *</label>
                            <input type="text" class="form-control" value="@kh.hoten">

                            <label>Email *</label>
                            <input type="email" class="form-control" required value="@kh.email">

                            <div class="row">
                                <div class="col-sm-6">
                                    <label>Tỉnh / Thành Phố *</label>
                                    <input type="text" class="form-control" name="thanhpho" required value="   @kh.tinh">
                                </div>

                                <div class="col-sm-6">
                                    <label>Quận / Huyện *</label>
                                    <input type="text" class="form-control" name="huyen" required value="@kh.huyen">
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-6">
                                    <label>Phường / Xã *</label>
                                    <input type="text" class="form-control" name="phuongxa" required value="@kh.xa">
                                </div>

                                <div class="col-sm-6">
                                    <label>Điện Thoại *</label>
                                    <input type="tel" class="form-control" name="dienthoai" required value="@kh.dienthoai">
                                </div>
                            </div>

                            <label>Địa Chỉ Cụ Thể (số nhà, thôn, xóm)</label>
                            <input type="text" name="diachi" class="form-control" value="@kh.thon" required>


                            <label>Ghi Chú</label>
                            <textarea class="form-control" cols="30" rows="4" placeholder="Ghi chú"></textarea>
                        </div>
                        <aside class="col-lg-5">
                            <div class="summary">
                                <h3 class="summary-title">Sản Phẩm Mua</h3>
                                <table class="table table-summary">
                                    <thead>
                                        <tr>
                                            <th>Tên Sản Phẩm</th>
                                            <th>Thành Tiền</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @if (Model != null && Model.Any())
                                        {
                                            foreach (var item in Model)
                                            {
                                                if (item.makhachhang.ToString() == Session["ma"].ToString())
                                                {
                                                    <tr>
                                                        <td>
                                                            <a href="~/SanPhams/Details/@item.masp">
                                                                @{ 
                                                                    string tensp = item.SanPham.tensp.ToString();
                                                                    string[] ten = tensp.Split('(');
                                                                    string tengon = ten[0];
                                                                }
                                                                @tengon
                                                            </a>
                                                        </td>
                                                        <td>
                                                            @{
                                                                decimal gia = (decimal)item.SanPham.giaban * item.soluong;
                                                                string giaformat = gia.ToString("#,##0");
                                                                TienHang = TienHang + gia;
                                                            }
                                                            @giaformat
                                                        </td>
                                                    </tr>
                                                }
                                            }
                                        }
                                        
                                        <tr>
                                            <td><b>Phí Vận chuyển:</b></td>
                                            <td>Miễn phí</td>
                                        </tr>
                                        <tr class="summary-total">
                                            <td>Tổng:</td>
                                            <td>
                                                @{    
                                                    string TienHangformat = TienHang.ToString("#,##0");
                                                }
                                                @TienHangformat
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>

                                <div class="accordion-summary" id="accordion-payment">
                                    @*<div class="card">
                                        <div class="card-header" id="heading-1">
                                            <h2 class="card-title">
                                                <a role="button" data-toggle="collapse" href="#collapse-1" aria-expanded="true" aria-controls="collapse-1">
                                                    Thanh toán khi nhận hàng
                                                </a>
                                            </h2>
                                        </div>
                                        <div id="collapse-1" class="collapse show" aria-labelledby="heading-1" data-parent="#accordion-payment">
                                            <div class="card-body">
                                                Vui lòng thanh toán @TienHangformat khi nhận hàng, cho phép <b>kiểm tra sản phẩm</b> trước khi thanh toán.
                                            </div>
                                        </div>
                                    </div>*@

                                    <div class="card">
                                        <div class="card-header" id="heading-2">
                                           
                                                <br />
                                                <input type="radio" id="cod" name="thanhtoan" value="cod" checked> <span style="font-size: 15px; margin-left: 3px;"> Thanh Toán Khi Nhận Hàng</span>
                                                <br />
                                                <br />
                                                <input type="radio" id="banking" name="thanhtoan" value="banking"> <span style="font-size: 15px; margin-left: 3px;">Thanh Toán Bằn Thẻ Tín Dụng VnPay</span>

                                         
                                            @*<h2 class="card-title">
                                                <a class="collapsed" role="button" data-toggle="collapse" href="#collapse-2" aria-expanded="false" aria-controls="collapse-2">
                                                    <input type="radio" id="cod" name="thanhtoan" checked> Thanh Toán Khi Nhận Hàng
                                                    <br />
                                                    <input type="radio" id="online" name="thanhtoan"> Thanh Toán Bằn Thẻ Tín Dụng VnPay
                                                </a>
                                            </h2>*@
                                        </div>
                                        @*<div id="collapse-2" class="collapse" aria-labelledby="heading-2" data-parent="#accordion-payment">
                                            <div class="card-body">
                                                Ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis.
                                            </div>
                                        </div>*@
                                    </div>

                                    @*<div class="card">
                                        <div class="card-header" id="heading-3">
                                            <h2 class="card-title">
                                                <a class="collapsed" role="button" data-toggle="collapse" href="#collapse-3" aria-expanded="false" aria-controls="collapse-3">
                                                    Thanh toán bằng Viettell Pay
                                                </a>
                                            </h2>
                                        </div>
                                        <div id="collapse-3" class="collapse" aria-labelledby="heading-3" data-parent="#accordion-payment">
                                            <div class="card-body">
                                                Quisque volutpat mattis eros. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros.
                                            </div>
                                        </div>
                                    </div>*@

                                    <!--<div class="card">
                                        <div class="card-header" id="heading-5">
                                            <h2 class="card-title">
                                                <a class="collapsed" role="button" data-toggle="collapse" href="#collapse-5" aria-expanded="false" aria-controls="collapse-5">
                                                    Credit Card (Stripe)
                                                    <img src="~/Content/assets/images/payments-summary.png" alt="payments cards">
                                                </a>
                                            </h2>
                                        </div>--><!-- End .card-header -->
                                        <!--<div id="collapse-5" class="collapse" aria-labelledby="heading-5" data-parent="#accordion-payment">
                                            <div class="card-body">
                                                Donec nec justo eget felis facilisis fermentum.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Lorem ipsum dolor sit ame.
                                            </div>--><!-- End .card-body -->
                                        <!--</div>--><!-- End .collapse -->
                                    <!--</div>--><!-- End .card -->
                                </div><!-- End .accordion -->

                                <button type="submit" class="btn btn-outline-primary-2 btn-order btn-block">
                                    <span class="btn-text">ĐẶT HÀNG</span>
                                    <span class="btn-hover-text">ĐẶT HÀNG</span>
                                </button>
                            </div>
                        </aside>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

Views/GioHangs/VnpayReturn.cshtml
@{
    ViewBag.Title = "VnpayReturn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>VnpayReturn</h2>