Models/TinTuc.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DoAn.Models
{
    [Table("TinTuc")]
    public partial class TinTuc
    {
        [Key]
        public int matintuc {  get; set; }

        [StringLength(500)]
        public string tieude { get; set; }

        [StringLength(50)]
        public string hinhanh { get; set; }

        public DateTime ngaytao { get; set; }
        public string gioithieu {  get; set; }

        public bool? trangthai { get; set; }
        public int makhachhang { get; set; }
        public string noidung {  get; set; }

        public virtual KhachHang KhachHang { get; set; }
    }
}

Areas/Admin/Controllers/TinTucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAn.Models;

namespace DoAn.Areas.Admin.Controllers
{
    public class TinTucsController : Controller
    {
        private Model1 db = new Model1();

        // GET: Admin/TinTucs
        public ActionResult Index()
        {
            var tinTucs = db.TinTucs.ToList();
            tinTucs = tinTucs.OrderByDescending(n => n.matintuc).ToList();
            return View(tinTucs);
        }

        // GET: Admin/TinTucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // GET: Admin/TinTucs/Create
        public ActionResult Create()
        {
            ViewBag.makhachhang = new SelectList(db.KhachHangs.Where(s => s.chucvu == true), "makhachhang", "hoten");
            List<SelectListItem> trangThaiList = new List<SelectListItem>
            {
                new SelectListItem { Value = "true", Text = "Hiển thị" },
                new SelectListItem { Value = "false", Text = "Ẩn" }
            };
            ViewBag.TrangThaiList = trangThaiList;
            return View();

        }

        // POST: Admin/TinTucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "matintuc,tieude,hinhanh,ngaytao,gioithieu,trangthai,makhachhang,noidung")] TinTuc tinTuc)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    tinTuc.hinhanh = "";
                    var file = Request.Files["ImageUpload"];
                    if (file != null && file.ContentLength > 0)
                    {
                        string filename = Path.GetFileName(file.FileName);
                        string filepath = Server.MapPath("~/wwwroot/tintuc/" + filename);
                        file.SaveAs(filepath);
                        tinTuc.hinhanh = filename;
                    }
                    tinTuc.ngaytao = DateTime.Now;
                    db.TinTucs.Add(tinTuc);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ViewBag.makhachhang = new SelectList(db.KhachHangs, "makhachhang", "hoten", tinTuc.makhachhang);
                return View(tinTuc);
            }
        }

        // GET: Admin/TinTucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            ViewBag.makhachhang = new SelectList(db.KhachHangs.Where(s => s.chucvu == true), "makhachhang", "hoten", tinTuc.makhachhang);
            List<SelectListItem> trangThaiList = new List<SelectListItem>
            {
                new SelectListItem { Value = "true", Text = "Hiển thị" },
                new SelectListItem { Value = "false", Text = "Ẩn" }
            };
            ViewBag.TrangThaiList = trangThaiList;
            return View(tinTuc);
        }

        // POST: Admin/TinTucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "matintuc,tieude,hinhanh,ngaytao,gioithieu,trangthai,makhachhang,noidung")] TinTuc tinTuc)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var file = Request.Files["ImageUpload"];
                    if (file != null && file.ContentLength > 0)
                    {
                        tinTuc.hinhanh = "";
                        string filename = Path.GetFileName(file.FileName);
                        string filepath = Server.MapPath("~/wwwroot/tintuc/" + filename);
                        file.SaveAs(filepath);
                        tinTuc.hinhanh = filename;
                    }
                    db.Entry(tinTuc).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ViewBag.makhachhang = new SelectList(db.KhachHangs, "makhachhang", "hoten", tinTuc.makhachhang);
                return View(tinTuc);

            }
        }

        // GET: Admin/TinTucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // POST: Admin/TinTucs/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TinTuc tinTuc = db.TinTucs.Find(id);
            db.TinTucs.Remove(tinTuc);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/TinTucs/Create.cshtml
@model DoAn.Models.TinTuc

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}

@section naviheader{
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Home" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="~/admin/sanphams" class="nav-link">Tin tức</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Thêm mới</a>
        </li>
    </ul>
}

<!-- Content Wrapper. Contains page content -->
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                @*<h1>Thêm mới danh mục</h1>*@
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/admin/sanphams">Quản lý sản phẩm</a></li>
                    <li class="breadcrumb-item active">Thêm mới</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông tin tin tức thêm mới</h3>
        </div>
        <div class="card-body">
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Create", "TinTucs", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Tiêu Đề</label>
                                @Html.EditorFor(model => model.tieude, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.tieude, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Hình Ảnh</label>
                                <br />
                                <img id="output" class="img-thumbnail" src="~/wwwroot/tintuc/no-image.png" width="200" height="200" />
                                <p><label for="ufile" style="cursor:pointer">Chọn hình ảnh</label></p>
                                <input type="file" id="ufile" name="ImageUpload" style="display: none" onchange="loadImage(event)" />
                                @*@Html.EditorFor(model => model.hinhanh, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.hinhanh, "", new { @class = "text-danger" })*@
                            </div>
                        </div>

                        @*<div class="form-group">
                                <div class="col-md-10">
                                    <label>Ngày Tạo</label>
                                    @Html.EditorFor(model => model.ngaytao, new { htmlAttributes = new { @class = "form-control"} })
                                    @Html.ValidationMessageFor(model => model.ngaytao, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Giới Thiệu</label>
                                @Html.EditorFor(model => model.gioithieu, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.gioithieu, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <div class="checkbox">
                                    <label>Trạng Thái</label>
                                    @Html.DropDownListFor(model => model.trangthai, (IEnumerable<SelectListItem>)ViewBag.TrangThaiList, htmlAttributes: new { @class = "form-control" })
                                    @*@Html.EditorFor(model => model.trangthai)*@
                                    @Html.ValidationMessageFor(model => model.trangthai, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Người Tạo</label>
                                @Html.DropDownList("makhachhang", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.makhachhang, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Nội Dung</label>
                                <br />
                                @Html.TextAreaFor(model => model.noidung, new
                                {
                                    htmlAttributes = new { @class = "form-control" },
                                                style = "width: 100%; height: 200px;"
                                })
                                @Html.ValidationMessageFor(model => model.noidung, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <br />
                        <div class="form-group">
                            <input type="submit" value="Thêm mới" class="btn btn-primary" />
                            <a href="/admin/sanphams" class="btn btn-danger">Quay lại</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

<script>
    var loadImage = function (event) {
        var image = document.getElementById("output");
        image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>

Areas/Admin/Views/TinTucs/Delete.cshtml
@model DoAn.Models.TinTuc

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TinTuc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KhachHang.hoten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHang.hoten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tieude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tieude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinhanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hinhanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngaytao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaytao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gioithieu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gioithieu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.trangthai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.trangthai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.noidung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.noidung)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/Admin/Views/TinTucs/Edit.cshtml
@model DoAn.Models.TinTuc

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section naviheader{
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="~/Admin/Home" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/KhachHangs" class="nav-link">Bài Viết</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Từ khóa tìm kiếm" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
    </ul>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">

            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/Admin/Home">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Quản lý bài viết</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông tin sản phẩm chỉnh sửa</h3>
        </div>

        <div class="card-body">
            <div class="bs-stepper-content">
                @using (Html.BeginForm("Edit", "TinTucs", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.matintuc)

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Tiêu đề</label>

                                @Html.EditorFor(model => model.tieude, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.tieude, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Hình ảnh</label>
                                @*@Html.EditorFor(model => model.hinhanh, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.hinhanh, "", new { @class = "text-danger" })*@
                                @{
                                    var ImagePath = "~/wwwroot/tintuc/" + Model.hinhanh;
                                }
                                <br />
                                <img id="output" class="img-thumbnail" src="@Url.Content("~/wwwroot/tintuc/" + Model.hinhanh)" width="200" height="200" />
                                <p><label for="ufile" style="cursor:pointer">Chọn hình ảnh</label></p>
                                <input type="file" id="ufile" name="ImageUpload" style="display: none" onchange="loadImage(event)" />
                            </div>
                        </div>

                        @*<div class="form-group">
                                <label>Ngày tạo</label>
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ngaytao, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ngaytao, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Giới thiệu</label>
                                @Html.EditorFor(model => model.gioithieu, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.gioithieu, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Người tạo</label>
                                @Html.DropDownList("makhachhang", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.makhachhang, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Trạng Thái</label>
                                <div class="checkbox">
                                    @Html.DropDownListFor(model => model.trangthai, (IEnumerable<SelectListItem>)ViewBag.TrangThaiList, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.trangthai, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-10">
                                <label>Nội dung</label>
                                <br />
                                @Html.TextAreaFor(model => model.noidung, new
                                {
                                    htmlAttributes = new { @class = "form-control" },
                                    style = "width: 100%; height: 200px;"
                                })
                                @Html.ValidationMessageFor(model => model.noidung, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Lưu" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
</section>
<script>
    var loadImage = function (event) {
        var image = document.getElementById("output");
        image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>

Areas/Admin/Views/TinTucs/Index.cshtml
@model IEnumerable<DoAn.Models.TinTuc>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="~/Admin/Home" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/KhachHangs" class="nav-link">Bài Viết</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Từ khóa tìm kiếm" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
    </ul>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">

            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/Admin/Home">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Quản lý bài viết</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><b>Danh sách bài viết</b></h3>

            <div class="card-tools">
                <a href="/admin/tintucs/create" class="btn btn-primary">Thêm mới</a>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-hover text-center">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Ảnh</th>
                        <th>Tiêu Đề</th>
                        <th>Ngày Tạo</th>
                        <th>Người Tạo</th>
                        <th>Trạng thái</th>
                        <th>Thực hiện</th>
                    </tr>
                </thead>
                @if (Model != null && Model.Any())
                {
                    var i = 1;
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @i
                            </td>
                            <td>
                                <img src="@Url.Content("~/wwwroot/tintuc/" + item.hinhanh)" class="img-rounded" width="150" height="150" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tieude)
                            </td>
                            <td>
                                @item.ngaytao.ToString("dd/MM/yyyy")
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.KhachHang.hoten)
                            </td>
                            @if (item.trangthai == true)
                            {
                                <td class="text-success">
                                    Hiển thị
                                </td>
                            }
                            else
                            {
                                <td class="text-danger">Ẩn</td>
                            }
                            <td>
                                <a href="/admin/tintucs/details/@item.matintuc" class="btn btn-dark">Chi tiết</a>
                                <a href="/admin/tintucs/edit/@item.matintuc" class="btn btn-primary">Sửa</a>
                                @*<a href="/admin/tintucs/delete/@item.matintuc" class="btn btn-danger">Xóa</a>*@
                                <input type="button" data-id="@item.matintuc" class="delete btn btn-danger" value="Xóa" />
                            </td>
                        </tr>
                        i++;
                    }
                }
                else
                {
                    <tr>
                        <td colspan="4">Không có bản ghi nào!!!</td>
                    </tr>
                }
            </table>
        </div>
    </div>
</section>

<script>
$(document).ready(function() {
    $('.delete').click(function() {
        var newid = $(this).data('id');

        if (confirm("Bạn có chắc chắn muốn xóa bài viết này?")) {
            $.ajax({
                url: '@Url.Action("DeleteConfirmed", "TinTucs")',
                type: 'POST',
                data: { id: newid },
                success: function(result) {
                    if (result.success) {
                        alert('Xóa bài viết thành công!');
                        window.location.reload(); // Tải lại trang
                    } else {
                        alert('Xóa bài viết thất bại!');
                    }
                },
                error: function() {
                    // Xử lý khi có lỗi xảy ra trong quá trình gửi yêu cầu
                    alert('Đã xảy ra lỗi!');
                }
            });
        }
    });
});
</script>