Models/DonHang.cs
namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("DonHang")]
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            DonHangChiTiets = new HashSet<DonHangChiTiet>();
        }

        [Key]
        public int madonhang { get; set; }

        public int makhachhang { get; set; }

        [StringLength(15)]
        public string dienthoai { get; set; }

        [StringLength(500)]
        public string diachi { get; set; }

        [Column(TypeName = "date")]
        public DateTime ngaydat { get; set; }

        [Column(TypeName = "date")]
        public DateTime ngaynhan { get; set; }

        [Required]
        [StringLength(150)]
        public string thanhtoan { get; set; }

        public int? soluongmua { get; set; }

        public decimal? tongtien { get; set; }

        public bool? trangthai { get; set; }

        public virtual KhachHang KhachHang { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangChiTiet> DonHangChiTiets { get; set; }
    }
}

Areas/Admin/Controllers/DonHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using DoAn.Models;
using PagedList;

namespace DoAn.Areas.Admin.Controllers
{
    public class DonHangsController : Controller
    {
        private Model1 db = new Model1();

        // GET: Admin/DonHangs
        public ActionResult Index(int? page)
        {
            //var donHangs = db.DonHangs.Include(d => d.KhachHang);
            var searchString = Request.Form["search"];
            ViewBag.CurrentFilter = searchString;

            var donhangs = db.DonHangs.Include(s => s.KhachHang).ToList();
            donhangs = donhangs.OrderByDescending(s =>s.madonhang).ToList();
            if (!string.IsNullOrEmpty(searchString))
            {
                donhangs = db.DonHangs.Where(sp => sp.dienthoai.Equals(searchString)).ToList();
            }

            int pageSize = 15; // Số lượng dữ liệu trên mỗi trang
            int pageNumber = (page ?? 1); // Trang hiện tại, nếu không được cung cấp thì mặc định là trang 1

            // Truy vấn dữ liệu từ nguồn dữ liệu và tạo đối tượng PagedList
            return View(donhangs.ToPagedList(pageNumber, pageSize));
            //return View(donHangs.ToList());
        }


        // GET: Admin/DonHangs/Details/5
        public ActionResult Details(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            List<DonHangChiTiet> listDHCT = new List<DonHangChiTiet>();
            listDHCT = db.DonHangChiTiets.Where(s => s.madonhang == id).ToList();
            ViewBag.DHCT = listDHCT;
            return View(donHang);
        }

        // GET: Admin/DonHangs/Create
        public ActionResult Create()
        {
            ViewBag.makhachhang = new SelectList(db.KhachHangs, "makhachhang", "hoten");
            return View();
        }

        // POST: Admin/DonHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "madonhang,makhachhang,dienthoai,diachi,ngaydat,ngaynhan,thanhtoan,soluongmua,tongtien,trangthai")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                db.DonHangs.Add(donHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.makhachhang = new SelectList(db.KhachHangs, "makhachhang", "hoten", donHang.makhachhang);
            return View(donHang);
        }

        // GET: Admin/DonHangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.makhachhang = new SelectList(db.KhachHangs, "makhachhang", "hoten", donHang.makhachhang);
            return View(donHang);
        }

        // POST: Admin/DonHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "madonhang,makhachhang,dienthoai,diachi,ngaydat,ngaynhan,thanhtoan,soluongmua,tongtien,trangthai")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.makhachhang = new SelectList(db.KhachHangs, "makhachhang", "hoten", donHang.makhachhang);
            return View(donHang);
        }

        // GET: Admin/DonHangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        // POST: Admin/DonHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DonHang donHang = db.DonHangs.Find(id);
            db.DonHangs.Remove(donHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult UpdateOrder(int id)
        {
            var donHang = db.DonHangs.Find(id);
            donHang.trangthai = true;
            db.SaveChanges();
            return Json(new {success = true});
        }
    }
}

Controllers/DonHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAn.Models;

namespace DoAn.Controllers
{
    public class DonHangsController : Controller
    {
        private Model1 db = new Model1();

        // GET: DonHangs
        public ActionResult Index()
        {
            List<DonHang> donHangs = db.DonHangs.Include(d => d.KhachHang).ToList();
            donHangs = donHangs.OrderByDescending(d => d.madonhang).ToList();
            return View(donHangs);
        }

        // GET: DonHangs/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    DonHang donHang = db.DonHangs.Find(id);
        //    if (donHang == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(donHang);
        //}

        //// GET: DonHangs/Create
        //public ActionResult Create()
        //{
        //    ViewBag.makhachhang = new SelectList(db.KhachHangs, "makhachhang", "hoten");
        //    return View();
        //}

        //// POST: DonHangs/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "madonhang,makhachhang,dienthoai,diachi,ngaydat,ngaynhan,thanhtoan,soluongmua,tongtien,trangthai")] DonHang donHang)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.DonHangs.Add(donHang);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.makhachhang = new SelectList(db.KhachHangs, "makhachhang", "hoten", donHang.makhachhang);
        //    return View(donHang);
        //}

        //// GET: DonHangs/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    DonHang donHang = db.DonHangs.Find(id);
        //    if (donHang == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.makhachhang = new SelectList(db.KhachHangs, "makhachhang", "hoten", donHang.makhachhang);
        //    return View(donHang);
        //}

        //// POST: DonHangs/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "madonhang,makhachhang,dienthoai,diachi,ngaydat,ngaynhan,thanhtoan,soluongmua,tongtien,trangthai")] DonHang donHang)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(donHang).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.makhachhang = new SelectList(db.KhachHangs, "makhachhang", "hoten", donHang.makhachhang);
        //    return View(donHang);
        //}

        //// GET: DonHangs/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    DonHang donHang = db.DonHangs.Find(id);
        //    if (donHang == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(donHang);
        //}

        //// POST: DonHangs/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    DonHang donHang = db.DonHangs.Find(id);
        //    db.DonHangs.Remove(donHang);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}

        public ActionResult ChiTietDonHang(int? id)
        {
            DonHang donHang = db.DonHangs.Find(id);
            List<DonHangChiTiet> listDHCT = new List<DonHangChiTiet>();
            listDHCT = db.DonHangChiTiets.Where(s => s.madonhang == id).ToList();
            ViewBag.DHCT = listDHCT;
            return View(donHang);
        }

        public ActionResult Huy(int id)
        {
            DonHang donHang = db.DonHangs.Find(id);
            //List<DonHangChiTiet> listDHCT = new List<DonHangChiTiet>();
            //listDHCT = db.DonHangChiTiets.Where(s => s.madonhang == id).ToList();
            //listDHCT.Clear();
            //db.DonHangs.Remove(donHang);
            donHang.trangthai = null;
            db.SaveChanges();
            return Json(new { success = true });
        }
    }
}

Views/DonHangs/ChiTietDonHang.cshtml
@model DoAn.Models.DonHang
@{
    ViewBag.Title = "ChiTietDonHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var dsDHCT = (List<DoAn.Models.DonHangChiTiet>)ViewBag.DHCT;
    decimal total = 0;
}

<main class="main">
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="~/DonHangs/Index">Đơn Hàng</a></li>
                <li class="breadcrumb-item active" aria-current="page">Chi Tiết Đơn Hàng</li>
            </ol>
        </div><!-- End .container -->
    </nav><!-- End .breadcrumb-nav -->

    <div class="page-content">
        <div class="checkout">
            <div class="container">
                <div class="row">
                    <aside class="col-lg-12">
                        <div class="summary">
                            <h4>Chi Tiết Hóa Đơn</h4>

                            <div class="row">
                                <div class="col-sm-6">
                                    <label><b>Họ Tên Người Mua:</b>  @Html.DisplayFor(model => model.KhachHang.hoten) </label>
                                </div>

                                <div class="col-sm-6">
                                    <label><b>Số Điện Thoại:</b>  @Html.DisplayFor(model => model.dienthoai)</label>
                                </div>
                            </div>

                            <label class="mt-1"><b>Địa Chỉ:</b>  @Html.DisplayFor(model => model.diachi)</label>

                            <div class="row mt-1">
                                <div class="col-sm-6">
                                    <label>
                                        <b>Ngày Đặt:</b>
                                        @{
                                            string date = Model.ngaydat.ToString("dd/MM/yyyy");
                                        }
                                        @date
                                    </label>
                                </div>

                                <div class="col-sm-6">
                                    <label>
                                        <b>Ngày Nhận Dự Kiến:</b>
                                        @{
                                            string datee = Model.ngaynhan.ToString("dd/MM/yyyy");
                                        }
                                        @datee
                                    </label>
                                </div>
                            </div>

                            <label class="mt-1"><b>Hình Thức Thanh Toán:</b>  @Html.DisplayFor(model => model.thanhtoan)</label>
                            <br />

                            <h2 class="checkout-title mt-1">Phí Vận Chuyển: Miễn phí</h2>


                            <h2 class="checkout-title mt-2 mb-2">Sản Phẩm Mua:</h2>
                            <table class="table table-summary">
                                <thead>
                                    <tr class="text-center">
                                        <th>STT</th>
                                        <th style="width: 20px;"></th>
                                        <th style="width: 500px;">Sản Phẩm</th>
                                        <th>Model sản phẩm</th>
                                        <th>Số Lượng</th>
                                        <th>Thành Tiền</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @if (Model != null)
                                    {
                                        var i = 1;
                                        foreach (var item in dsDHCT)
                                        {
                                            <tr class="text-center">
                                                <td>
                                                    @i
                                                </td>
                                                <td></td>
                                                <td class="product-col">
                                                    <div class="product">
                                                        <figure class="product-media">
                                                            <a href="#">
                                                                <img src="@Url.Content("~/wwwroot/images/" + item.SanPham.hinhanh)" alt="Product image">
                                                            </a>
                                                        </figure>

                                                        <h3 class="product-title">
                                                            <a href="#">
                                                                @{
                                                                    string tensp = item.SanPham.tensp.ToString();
                                                                    string[] ten = tensp.Split('(');
                                                                    string tengon = ten[0];
                                                                }
                                                                @tengon
                                                            </a>
                                                        </h3><!-- End .product-title -->
                                                    </div><!-- End .product -->
                                                </td>
                                                <td>
                                                    @item.SanPham.model
                                                </td>
                                                <td class="quantity-col text-center">
                                                    @item.soluong
                                                </td>


                                                <td class="total-col">
                                                    @{
                                                        var thanhtien = item.soluong * item.SanPham.giaban;
                                                        total = total + (decimal)thanhtien;
                                                        decimal t = (decimal)thanhtien;
                                                        string formattedPrice = t.ToString("#,##0");

                                                    }
                                                    @formattedPrice đ
                                                </td>
                                            </tr>
                                            i++;

                                        }
                                    }
                                </tbody>
                            </table>

                            <h2 class="checkout-title total-col mt-5 mb-5">
                                @{
                                    string TT = total.ToString("#,##0");
                                }
                                Tổng Hóa Đơn: <span class="text-primary">@TT đ</span>

                            </h2>

                            @if (Model.trangthai == false)
                            {
                                <button type="submit" class="btn btn-outline-primary-2 btn-order btn-block" data-orderid="@Model.madonhang">
                                    <span class="btn-text">Xác Nhận Hủy</span>
                                    <span class="btn-hover-text">Xác Nhận Hủy</span>
                                </button>
                            }
                            else if (Model.trangthai == true)
                            {
                                <button type="submit" class="btn btn-outline-primary-2 btn-block" data-orderid="@Model.madonhang">
                                    <span class="btn-text">Mua Lại</span>
                                    <span class="btn-hover-text">Mua Lại</span>
                                </button>
                            }
                            else
                            {
                                <button type="submit" class="btn btn-outline-primary-2 btn-block" data-orderid="@Model.madonhang">
                                    <span class="text-danger">Đã Hủy</span>
                                </button>
                            }
                        </div>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</main>

<script>
    $(document).ready(function(){
        $('.btn-order').click(function () {
            var orderID = $(this).data('orderid');
            console.log(orderID);
            if (confirm("Bạn có chắc muốn hủy đơn này?")) {
                $.ajax({
                    url: '@Url.Action("Huy", "DonHangs")',
                    type: 'POST',
                    data: { id: orderID },
                    success: function (result) {
                        if (result.success) {
                            alert("Hủy thành công");
                            window.location.href = '/DonHangs/Index';
                        }
                        else {
                            alert("Xóa tài khoản thất bại");
                        }
                    },
                    Error: function () {
                        alert("Đã xảy ra lỗi!");
                    }
                });
            }
        });
    });
</script>

Views/DonHangs/Index.cshtml
@model IEnumerable<DoAn.Models.DonHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<main class="main">
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">Đơn Hàng</li>
            </ol>
        </div><!-- End .container -->
    </nav><!-- End .breadcrumb-nav -->

    <div class="page-content">
        <div class="cart">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <table class="table table-cart table-mobile">
                            <thead>
                                <tr>
                                    <th>Họ Tên</th>
                                    <th>Điện Thoại</th>
                                    <th>Địa Chỉ</th>
                                    <th>Ngày Đặt</th>
                                    @*<th>Hình Thức Thanh Toán</th>*@
                                    <th>Tổng Tiền</th>
                                    <th>Trạng Thái</th>
                                    <th></th>
                                </tr>
                            </thead>

                            <tbody>
                                @if (Model != null && Model.Any())
                                {
                                    foreach (var item in Model)
                                    {
                                        if (item.makhachhang.ToString() == Session["ma"].ToString())
                                        {
                                            @*<tr class="donhangchitiet" data-donhang-id="@item.madonhang">*@
                                            <tr>
                                                <td>@item.KhachHang.hoten</td>
                                                <td>@item.dienthoai</td>
                                                <td>@item.diachi</td>
                                                <td>
                                                    @{
                                                        string date = item.ngaydat.ToString("dd/MM/yyyy");
                                                    }
                                                    @date
                                                </td>
                                                @*<td>@item.thanhtoan</td>*@
                                                <td>
                                                    @{
                                                        if (item.tongtien == null)
                                                        {
                                                            item.tongtien = 0;
                                                        }
                                                        decimal total = (decimal)item.tongtien;
                                                        string totalformat = total.ToString("#,##0");

                                                    }
                                                    @totalformat đ
                                                </td>

                                                @if (item.trangthai == false)
                                                {
                                                    <td class="text-primary">Đang giao</td>
                                                }

                                                else if (item.trangthai == true)
                                                {
                                                    <td class="text-success">Đã giao</td>
                                                }
                                                else
                                                {
                                                    <td class="text-danger">Đã hủy</td>
                                                }
                                                <td class="remove-col"><a href="~/DonHangs/ChiTietDonHang/@item.madonhang" class="btn-remove"><ion-icon name="ellipsis-vertical-outline"></ion-icon></a></td>
                                            </tr>
                                        }
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td colspan="8"><h5>Bạn chưa có đơn hàng nào !</h5></td>
                                    </tr>
                                }
                            </tbody>
                            </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<style>
    .donhangchitiet:hover
    {
        cursor: pointer;
    }
</style>

@*<script>
    $(document).ready(function() {
        $('.donhangchitiet').click(function() {
            var OrderId = $(this).data('donhang-id');
            // Gửi yêu cầu thêm sản phẩm vào giỏ hàng bằng AJAX
            $.ajax({
                url: '@Url.Action("ChiTietDonHang", "DonHangs")',
                type: 'POST',
                data: { id: OrderId },
                success: function(result) {
                    if (result.success) {
                        // Xử lý khi thêm thành công
                        window.location.href = '/DonHangs/ChiTietDonHang/' + OrderId;

                    }
                },
                error: function() {
                    // Xử lý khi có lỗi xảy ra trong quá trình gửi yêu cầu
                    alert('Đã xảy ra lỗi!');
                }
            });

        });
});
</script>*@